# Generated by Django 4.2.1 on 2023-06-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_blog_autor_alter_projetos_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comentario',
        ),
    ]
